title: Stackbit Fresh Theme
baseURL: /
params:
  layout_style: overflow
  palette: blue
  header:
    title: Ben Halpern
    tagline: A Canadian software developer who thinks he’s funny.
    profile_img: >-
      https://res.cloudinary.com/practicaldev/image/fetch/s--DOU9qJSH--/c_fill,f_auto,fl_progressive,h_320,q_auto,w_320/https://thepracticaldev.s3.amazonaws.com/uploads/user/profile_image/1/f451a206-11c8-4e3d-8936-143d0a7e65bb.png
    bg: dark
    has_nav: true
    has_social: true
  footer:
    content: '&copy; All rights reserved.'
    links:
      - text: Made with Stackbit
        url: 'https://www.stackbit.com'
        new_window: true
disableKinds:
  - RSS
